---
apiVersion: v1
kind: Service
metadata:
  name: conjur-postgres
  labels:
    app: conjur-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: conjur-postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-postgres
  labels:
    app: conjur-postgres
spec:
  selector:
    matchLabels:
      app: conjur-postgres
      name: conjur-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-postgres
        name: conjur-postgres
    spec:
      serviceAccountName: conjur-cluster
      containers:
        - name: postgres
          image: postgres:9.4
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
              #environment:
              # To avoid the following error:
              #
              #   Error: Database is uninitialized and superuser password is not
              #   specified.  You must specify POSTGRES_PASSWORD for the superuser. Use
              #   "-e POSTGRES_PASSWORD=password" to set it in "docker run".
              #
              #   You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all
              #   connections without a password. This is *not* recommended. See
            #   PostgreSQL documentation about "trust"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
